language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: TOXENV=WIN
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y g++-mingw-w64 cmake git build-essential autoconf texinfo bison flex; fi
addons:
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake
- cmake --build . -- vita-toolchain_build
- cmake --build . -- vita-toolchain_host
