language: cpp
os: osx
osx_image: xcode8.3

before_script:
- export PATH="$HOME/bin:$PATH"
- make -f texinfo-travis.mk install_texinfo
script:
- export REV=dirty-$(git describe --always)
- git clone https://github.com/vitasdk/buildscripts.git
- chmod +x *.sh
- "./build.sh"
